server:
  port: 8500

spring:
  application:
    name: codebox-cloud-config
  profiles:
    active: native
  banner:
    location: classpath:/banner/banner.txt

---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${codebox.config.dir}

codebox:
  config:
    dir: D:/workspace/codebox/codebox.config

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stag

---
spring:
  config:
    activate:
      on-profile: prod